In [1]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


In [28]:
def relu(s):
    return np.maximum(0,s)

def l2_loss(y,y_pred):
    diff = y - y_pred
    return 0.5 * diff.dot(diff.T)

In [29]:
# Init
X = np.array([[0.75, 0.80], 
              [0.20, 0.05], 
              [-0.75, 0.80], 
              [0.20, -0.05]]).T
y = np.array([1, 1, -1, -1]).T

W_1 = np.array([[0.6, 0.7, 0.0],[0.01, 0.43, 0.88]]).T
W_2 = np.array([[0.02, 0.03, 0.09]])

print('X', X.shape)
print('y', y.shape)
print('W_1', W_1.shape)
print('W_2', W_2.shape)

X (2, 4)
y (4,)
W_1 (3, 2)
W_2 (1, 3)


## Forward

In [30]:
s = W_1.dot(X)
z = relu(s)

print('s = W.X', s.shape, '\n', s)
print('z=relu(s)', z.shape,  '\n', z)

s_out = W_2.dot(z)
y_out = z_out = s_out

print('s_out = W_2.z', s_out.shape, '\n', s_out)
print('z_out=linear(s_out)', z_out.shape,  '\n', z_out)

loss = l2_loss(y, y_out)
print('Loss', loss.shape, '\n', loss)

s = W.X (3, 4) 
 [[ 0.458   0.1205 -0.442   0.1195]
 [ 0.869   0.1615 -0.181   0.1185]
 [ 0.704   0.044   0.704  -0.044 ]]
z=relu(s) (3, 4) 
 [[ 0.458   0.1205  0.      0.1195]
 [ 0.869   0.1615  0.      0.1185]
 [ 0.704   0.044   0.704   0.    ]]
s_out = W_2.z (1, 4) 
 [[ 0.09859   0.011215  0.06336   0.005945]]
z_out=linear(s_out) (1, 4) 
 [[ 0.09859   0.011215  0.06336   0.005945]]
Loss (1, 1) 
 [[ 1.9664478]]


### Backward

In [31]:
dL_dYout = y_out - y
delta_out = dL_dSout = dL_dYout

dL_dW2 = delta_out.dot(z.T)

# relu derivative
dL_dZ = np.where(s>0, np.ones(s.shape), 0)
delta_1 = dL_dS = W_2.T.dot(delta_out) * dL_dZ

dL_dW1 = delta_1.dot(X.T)

In [32]:
print('dL_dYout \n',dL_dYout)
print('delta_out \n',delta_out)
print('dL_dW2 \n',dL_dW2)
print('delta_1 \n',delta_1)
print('dL_dW1 \n',dL_dW1)

dL_dYout 
 [[-0.90141  -0.988785  1.06336   1.005945]]
delta_out 
 [[-0.90141  -0.988785  1.06336   1.005945]]
dL_dW2 
 [[-0.41178394 -0.82380959  0.07050626]]
delta_1 
 [[-0.0180282  -0.0197757   0.          0.0201189 ]
 [-0.0270423  -0.02966355  0.          0.03017835]
 [-0.0811269  -0.08899065  0.0957024   0.        ]]
dL_dW1 
 [[-0.01345251 -0.01641729]
 [-0.02017877 -0.02462594]
 [-0.1504201   0.00721087]]


In [33]:
W_2 -= 0.5 * dL_dW2
W_1 -= 0.5 * dL_dW1

print('W_2 \n',W_2)
print('W_1 \n',W_1)

W_2 
 [[ 0.22589197  0.44190479  0.05474687]]
W_1 
 [[ 0.60672625  0.01820865]
 [ 0.71008938  0.44231297]
 [ 0.07521005  0.87639457]]
