In [2]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


In [35]:
def relu(s):
    return np.maximum(0,s)

def l2_loss(y,y_pred):
    diff = y - y_pred
    return 0.5 ** diff.dot(diff.T)

In [44]:
# Init
X = np.array([[0.75, 0.80], 
              [0.20, 0.05], 
              [-0.75, 0.80], 
              [0.20, -0.05]]).T
y = np.array([1, 1, -1, -1]).T

W_1 = np.array([[0.6, 0.7, 0.0],[0.01, 0.43, 0.88]]).T
W_2 = np.array([[0.02, 0.03, 0.09]])

print('X', X.shape)
print('y', y.shape)
print('W_1', W_1.shape)
print('W_2', W_2.shape)

X (2, 4)
y (4,)
W_1 (3, 2)
W_2 (1, 3)


In [45]:
s = W_1.dot(X)
z = relu(s)

print('s = W.X', s.shape, '\n', s)
print('z=relu(s)', z.shape,  '\n', z)

s_out = W_2.dot(z)
y_out = z_out = s_out

print('s_out = W_2.z', s_out.shape, '\n', s_out)
print('z_out=linear(s_out)', z_out.shape,  '\n', z_out)

loss = l2_loss(y, y_out)
print('Loss', loss.shape, '\n', loss)

s = W.X (3, 4) 
 [[ 0.458   0.1205 -0.442   0.1195]
 [ 0.869   0.1615 -0.181   0.1185]
 [ 0.704   0.044   0.704  -0.044 ]]
z=relu(s) (3, 4) 
 [[ 0.458   0.1205  0.      0.1195]
 [ 0.869   0.1615  0.      0.1185]
 [ 0.704   0.044   0.704   0.    ]]
s_out = W_2.z (1, 4) 
 [[ 0.09859   0.011215  0.06336   0.005945]]
z_out=linear(s_out) (1, 4) 
 [[ 0.09859   0.011215  0.06336   0.005945]]
(1, 4)
Loss (1, 1) 
 [[ 0.06547575]]
